spring.application.name=pdvapi
spring.datasource.url=jdbc:postgresql://localhost:5432/pdv
spring.datasource.username=postgresql
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver